# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-480d5be8-2801-49bf-8a04-f25c9b8c3de1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-480d5be8-2801-49bf-8a04-f25c9b8c3de1".device = "/dev/disk/by-uuid/480d5be8-2801-49bf-8a04-f25c9b8c3de1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BEEC-5DEA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  powerManagement.enable = true;
  services.thermald.enable = true;


  services.tlp = {
      enable = true;
      pd.enable = true;
      settings = {
        CPU_SCALING_GOVERNOR_ON_AC = "balanced";
        CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

        CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
        CPU_ENERGY_PERF_POLICY_ON_AC = "balanced";

        CPU_MIN_PERF_ON_AC = 0;
        CPU_MAX_PERF_ON_AC = 100;
        CPU_MIN_PERF_ON_BAT = 0;
        CPU_MAX_PERF_ON_BAT = 20;

       #Optional helps save long term battery health
       START_CHARGE_THRESH_BAT0 = 40; # 40 and below it starts to charge
       STOP_CHARGE_THRESH_BAT0 = 80; # 80 and above it stops charging

      };
  };

  security.sudo.extraRules = [
    {
      users = [ "troels" ];
      commands = [
        { command = "/run/current-system/sw/bin/tlp performance"; options = [ "NOPASSWD" ]; }
        { command = "/run/current-system/sw/bin/tlp balanced"; options = [ "NOPASSWD" ]; }
        { command = "/run/current-system/sw/bin/tlp power-saver"; options = [ "NOPASSWD" ]; }
      ];
    }
  ];

  services.logind.powerKey = "ignore";
}
